name: SKO-CI/CD

on:
  push:
    branches:
      - Jay
  pull_request:
    branches:
      - Jay

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.^' # Sesuaikan dengan versi PHP proyek Anda
        extensions: mbstring, bcmath, xml, curl, dom, json, pdo, pdo_mysql, tokenizer

    - name: Set up Node.js
      uses: actions/setup-node@v2
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.^' # Sesuaikan dengan versi PHP proyek Anda
        extensions: mbstring, bcmath, xml, curl, dom, json, pdo, pdo_mysql, tokenizer

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.2' # Sesuaikan dengan versi Node.js proyek Anda

    - name: Composer Update
      run : composer update
      
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-interaction

    - name: Install NPM dependencies
      run: npm install

    - name: Build assets with Laravel Mix
      run: npm run production

    - name: Set up .env
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Run Laravel migrations
      run: php artisan migrate --force
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: root

    - name: Run Laravel tests
        cp .env.example .env
        php artisan key:generate

    - name: Run Laravel migrations
      run: php artisan migrate --force
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: root

    - name: Run Laravel tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan test
