name: LARAVEL_CD

on:
  push:
    branches:
    - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.devtribe.my.id
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 21
